name: Build And Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node-build:
    name: Build for production
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: build file on server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          command: |
            cd CE-BoostUp-XIII-DiscordBot/
            git pull origin main
            pm2 restart app 
